# common wifi and network settings
dashboard_import:
  package_import_url: github://teekennedy/home-assistant/esphome/packages/network.yaml

esphome:
  project:
    name: "teekennedy.network"
    version: "1.0.0"

substitutions:
  # Device name / hostname
  name: "my-esphome-device"
  # Password for the fallback hotspot.
  wifi_ap_password: null
  # Encryption key for API communications. Use unique key per host for maximum security.
  esphome_api_encryption_key: null
  # Password for OTA updates. Use unique password per host for maximum security.
  ota_esphome_password: null

# https://esphome.io/components/wifi.html#configuration-variables
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Allow rapid re-connection to previously connect WiFi SSID
  fast_connect: true
  # Define dns domain / suffix to add to hostname
  domain: ".lan"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: "${wifi_ap_password}"
    
# Fallback to captive portal after 1 minute of failed wifi connection attempts
# https://esphome.io/components/captive_portal.html
captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: "${esphome_api_encryption_key}"

network:
  enable_ipv6: true

# Disable mDNS - we're using ping to check whether this device is online or not.
mdns:
  disabled: true

ota:
  - platform: esphome
    id: ota_esphome
    password: "${ota_esphome_password}"
