# common wifi settings
# https://esphome.io/components/wifi.html#configuration-variables
dashboard_import:
  package_import_url: github://teekennedy/home-assistant/esphome/packages/wifi.yaml

esphome:
  project:
    name: "teekennedy.wifi"
    version: "1.0.0"

substitutions:
  # Device name / hostname
  name: "my-esphome-device"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Allow rapid re-connection to previously connect WiFi SSID
  fast_connect: true
  # Define dns domain / suffix to add to hostname
  domain: ".lan"
  # Connect to device using its local DNS entry
  use_address: "${name}.lan"

network:
  enable_ipv6: true

# Disable mDNS - we're using ping to check whether this device is online or not.
mdns:
  disabled: true
